### ISSUE TITLE
Implementation TODO List

### ISSUE THREAD

**Issue by linD026** [linD026/mthpc#7]
## Doc
- [ ] Write the formal doc for user APIs

## Safe ptr
- [x] implement the cmpxchg operation
- [ ] write side wait-free level

**Comment by linD026** [comment]
MacOS sched:
https://www.hybridkernel.com/2015/01/18/binding_threads_to_cores_osx.html
